Repository aenniw/ARDUINO, pull requests merged in 2018-10, with the labels that each got.

#13 Bug/psu reference
  skarsta/README.md
Labels: bug

#12 Feature/tmc rework
  lib/Grove 4-Digit Display_ID5064/TM1637.cpp
  lib/Grove 4-Digit Display_ID5064/TM1637.h
  lib/TM1637/LICENSE
  lib/TM1637/SevenSegmentTM1637.cpp
  lib/TM1637/SevenSegmentTM1637.h
  skarsta/README.md
  skarsta/lib/display/Display.cpp
  skarsta/lib/display/Display.h
  skarsta/lib/keypad/Keypad.cpp
  skarsta/lib/keypad/Keypad.h
  skarsta/lib/motor/Motor.cpp
  skarsta/lib/motor/Motor.h
  skarsta/lib/service/Service.h
  skarsta/platformio.ini
  skarsta/src/skarsta.cpp
Labels: bug, enhancement

#11 add panel with brideholes, scaled models
  skarsta/README.md
  skarsta/models/keypad-connector.stl
  skarsta/models/panel-cover-bridge.stl
  skarsta/models/table-frame-tie.stl
Labels: bug, enhancement

#16 Add press motor stop upon each press
  skarsta/lib/buttons/Buttons.cpp
  skarsta/lib/keypad/Keypad.cpp
  skarsta/lib/keypad/Keypad.h
Labels: enhancement
