Repository aenniw/ARDUINO, pull requests merged in 2021-08, with the labels that each got.

#137 SKARSTA: Adding functionality to control the table with serial communication
  skarsta/lib/motor/Motor.cpp
  skarsta/lib/motor/Motor.h
  skarsta/lib/serial/SerialCom.cpp
  skarsta/lib/serial/SerialCom.h
  skarsta/src/configuration.h
  skarsta/src/main.cpp
Labels: enhancement

#145 Add SerialCom docs
  skarsta/README.md
  skarsta/configs/nanoatmega328.ini
  skarsta/docs/serial-control.md
  skarsta/lib/motor/Motor.cpp
  skarsta/lib/motor/Motor.h
  skarsta/lib/serial/SerialCom.cpp
  skarsta/lib/serial/SerialCom.h
  skarsta/src/configuration.h
  skarsta/src/main.cpp
Labels: bug, enhancement, docs

#130 Add modular skarsta designs
  README.md
  skarsta/README.md
  skarsta/docs/case_bridge-v1.md
  skarsta/docs/case_bridge-v2.md
  skarsta/docs/case_motor-v2.md
  skarsta/docs/case_relays-v1.md
  skarsta/docs/case_relays-v2.md
  skarsta/docs/img/case_bridge-v2/case.jpg
  skarsta/docs/img/case_bridge-v2/connectors.jpg
  skarsta/docs/img/case_bridge-v2/electronics-1.jpg
  skarsta/docs/img/case_bridge-v2/electronics-2.jpg
  skarsta/docs/img/case_bridge-v2/electronics-3.jpg
  skarsta/docs/img/case_bridge-v2/electronics-4.jpg
  skarsta/docs/img/case_bridge-v2/mount.jpg
  skarsta/docs/img/case_motor-v2/mount-1.jpg
  skarsta/docs/img/case_motor-v2/mount-2.jpg
  skarsta/docs/img/case_motor-v2/mount-3.jpg
  skarsta/docs/img/case_motor-v2/mounted.jpg
  skarsta/docs/img/case_motor-v2/shaft.jpg
  skarsta/docs/img/case_motor-v2/sleeve.jpg
  skarsta/docs/img/case_relays-v2/case.jpg
  skarsta/docs/img/case_relays-v2/connectors.jpg
  skarsta/docs/img/case_relays-v2/electronics-1.jpg
  skarsta/docs/img/case_relays-v2/electronics-2.jpg
  skarsta/docs/img/case_relays-v2/electronics-3.jpg
  skarsta/docs/img/case_relays-v2/electronics-4.jpg
  skarsta/docs/img/case_relays-v2/mount.jpg
  skarsta/docs/img/sensor-rot/mounted.jpg
  skarsta/docs/panel-v2.md
  skarsta/docs/sensor-rot.md
  skarsta/models/ecase/ecase-bridge.stl
  skarsta/models/ecase/ecase-relay.stl
  skarsta/models/ecase/emount.stl
  skarsta/models/motor/motor-cover.stl
  skarsta/models/motor/motor-lock.stl
  skarsta/models/motor/motor-mount.stl
  skarsta/models/motor/motor-sleeve.stl
  skarsta/models/shaft-template.stl
Labels: enhancement, bom
